FizzBuzz/FizzBuzz.WebUi/ViewModels/FizzBuzz/FizzBuzzViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using FizzBuzz.Domain.Models;

namespace FizzBuzz.WebUi.ViewModels.FizzBuzz
{
    public class FizzBuzzViewModel
    {
        public FizzBuzzViewModel()
        {
            MaxValue = string.Empty;
            FizzWord = string.Empty;
            BuzzWord = string.Empty;
            PageNumber = 1;
            FizzBuzzItems = new List<(int, FizzBuzzType)>();
        }
        
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter a number")]
        [Range(1, 1000, ErrorMessage = "Please enter a number between 1 and 1000")]
        public string MaxValue { get; set; }

        public string FizzWord { get; set; }

        public string BuzzWord { get; set; }
        
        public int PageNumber { get; set; }

        public bool HasPreviousPage { get; set; }

        public bool HasNextPage { get; set; }

        public IEnumerable<(int, FizzBuzzType)> FizzBuzzItems { get; set; }
    }
}

FizzBuzz/FizzBuzz.WebUi/Controllers/FizzBuzzController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using FizzBuzz.Domain.Abstract;
using FizzBuzz.WebUi.ViewModels.FizzBuzz;

namespace FizzBuzz.WebUi.Controllers
{
    public class FizzBuzzController : Controller
    {
        private readonly IFizzBuzzGenerator _fizzBuzzGenerator;
        private readonly ISettingsStore _settingsStore;
        private readonly IPager _pager;
        private readonly IUserInputLogger _userInputLogger;

        public FizzBuzzController(
            IFizzBuzzGenerator fizzBuzzGenerator, 
            ISettingsStore settingsStore, 
            IPager pager,
            IUserInputLogger userInputLogger)
        {
            _fizzBuzzGenerator = fizzBuzzGenerator ?? throw new ArgumentNullException(nameof(fizzBuzzGenerator));
            _settingsStore = settingsStore ?? throw new ArgumentNullException(nameof(settingsStore));
            _pager = pager ?? throw new ArgumentNullException(nameof(pager));
            _userInputLogger = userInputLogger ?? throw new ArgumentNullException(nameof(userInputLogger));
        }

        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";
            return View("Results", new FizzBuzzViewModel());
        }

        public async Task<ActionResult> Results(FizzBuzzViewModel model)
        {
            if (model == null) throw new ArgumentNullException(nameof(model));

            ViewBag.Title = "Results Page";
            if (ModelState.IsValid)
            {
                var maxValue = Convert.ToInt32(model.MaxValue);
                var items = _fizzBuzzGenerator.Generate(1, maxValue);
                if (_pager.HasPage(items, 20, model.PageNumber))
                {
                    await _userInputLogger.LogAsync(maxValue, model.PageNumber);
                    return View(new FizzBuzzViewModel
                    {
                        MaxValue = model.MaxValue,
                        FizzWord = _settingsStore.FizzWord,
                        BuzzWord = _settingsStore.BuzzWord,
                        FizzBuzzItems = _pager.GetPage(items, 20, model.PageNumber),
                        PageNumber = model.PageNumber,
                        HasPreviousPage = _pager.HasPage(items, 20, model.PageNumber-1),
                        HasNextPage = _pager.HasPage(items, 20, model.PageNumber + 1)
                    });    
                }
                return RedirectToAction("Results", new {MaxValue = model.MaxValue, PageNumber = 1});
            }
            return View(new FizzBuzzViewModel
            {
                MaxValue = model.MaxValue
            });
        }
    }
}

FizzBuzz/FizzBuzz.WebUi/Views/FizzBuzz/Results.cshtml
@using FizzBuzz.Domain.Models
@model FizzBuzz.WebUi.ViewModels.FizzBuzz.FizzBuzzViewModel

@using (Html.BeginForm("Results", "FizzBuzz", FormMethod.Get))
{
    @Html.TextBoxFor(m => m.MaxValue, new {type="number", placeholder="Enter max value", autocomplete = "off", autofocus="" })
    @Html.ValidationMessageFor(m => m.MaxValue, null, new { id="max-value-error", @class="error"})
    <input type="submit" value="Submit" />
}
@if (Model.FizzBuzzItems.Any())
{
    <div id="results">
        <div id="description">Showing @Model.FizzWord @Model.BuzzWord sequence up to: <b id="current-max-value">@Model.MaxValue</b></div>
        <ul id="items">
            @foreach (var (number, type) in Model.FizzBuzzItems)
            {
                <li class="item">
                    @switch (type)
                    {
                        case FizzBuzzType.Fizz:
                            <span class="fizz">@Model.FizzWord</span>
                            break;
                        case FizzBuzzType.Buzz:
                            <span class="buzz">@Model.BuzzWord</span>
                            break;
                        case FizzBuzzType.FizzBuzz:
                            <span class="fizz">@Model.FizzWord</span>@Html.Raw("&nbsp;")<span class="buzz">@Model.BuzzWord</span>
                            break;
                        default:
                            @number
                            break;
                    }
                </li>
            }
        </ul>
        @if (Model.HasNextPage || Model.HasPreviousPage)
        {
            <div class="pager">
                <div class="current-page">
                    Current page: <b class="current-page-number">@Model.PageNumber</b>
                </div>
                @if (Model.HasNextPage || Model.HasPreviousPage)
                {
                    <div class="page-links">
                        @if (Model.HasPreviousPage)
                        {
                            <a class="previous-page" href="@Url.Action("Results", "FizzBuzz", new {MaxValue = Model.MaxValue, PageNumber = Model.PageNumber - 1})">
                                &#xab;&nbsp;Previous page
                            </a>
                        }
                        else
                        {
                            <div class="previous-page disabled">&#xab; Previous page</div>
                        }
                        @if (Model.HasNextPage)
                        {
                            <a class="next-page" href="@Url.Action("Results", "FizzBuzz", new {MaxValue = Model.MaxValue, PageNumber = Model.PageNumber + 1})">
                                Next page&nbsp;&#xbb;
                            </a>
                        }
                        else
                        {
                            <div class="next-page disabled">&#xab; Next page</div>
                        }
                    </div>
                }
            </div>
        }
    </div>
}

FizzBuzz/FizzBuzz.WebUi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="container">
        <h1 class="banner">{C.H}</h1>
        <h2 class="title">Fizz Buzz</h2>
        <main>
            @RenderBody()
        </main>
    </div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
</body>
</html>